name: Build docs

# Runs on pushes targeting the default branch
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

# Cancel in-progress runs when pushing a new commit on the PR
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip' # caching pip dependencies

      - name: Install deepinv and its dependencies
        run: |
          pip install -e .[dataset,denoisers,doc]
#      - name: Sphinx build
#        run: |
#          sphinx-build -W docs/source _build
      - name: Sphinx build (fast)
        run: |
          sphinx-build -W -D plot_gallery=0 docs/source _build
      - name: Run doctests
        run: |
          # Get all the RST files, excluding multigpu.rst
          # and *datasets.rst files
          _doctest_files=$(find . -name '*.rst' ! -name '*multigpu.rst' ! -name '*datasets*.rst')
          # Run doctest with sphinx, to get the extra IGNORE_OUTPUT primitive
          # using plot_gallery=0 to avoid building examples
          sphinx-build -M doctest docs/source/ docs/build/ -D plot_gallery=0 -v $_doctest_files
#      - name: Deploy preview
#        uses: JamesIves/github-pages-deploy-action@v4
#        if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/main' }}
#        with:
#          folder: .
#          branch: gh-pages
#          clean-exclude: pr-preview
#          force: false
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          exclude_assets: 'pr-preview'
          force_orphan: true
          enable_jekyll: false
