# .github/workflows/preview.yml
name: Deploy PR previews

# Cancel in-progress runs when pushing a new commit on the PR
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed


permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip' # caching pip dependencies

      - name: Install deepinv and its dependencies
        run: |
          pip install -e .[dataset,denoisers,doc]
      - name: Sphinx build
        run: |
          sphinx-build -W -D plot_gallery=0 docs/source _build
      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: .
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
