# .github/workflows/preview.yml
name: Deploy PR previews

# Cancel in-progress runs when pushing a new commit on the PR
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed


permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip' # caching pip dependencies

      - name: Install deepinv and its dependencies
        run: |
          pip install -e .[dataset,denoisers,doc]
#      - name: Sphinx build
#        run: |
#          sphinx-build -W docs/source _build
      - name: Sphinx build
        run: |
            cd docs;
            make SPHINXOPTS=-v html-fast;
            cd ..;
#      - name: Run doctests
#        run: |
#          # Get all the RST files, excluding multigpu.rst
#          # and *datasets.rst files
#          _doctest_files=$(find . -name '*.rst' ! -name '*multigpu.rst' ! -name '*datasets*.rst')
#          # Run doctest with sphinx, to get the extra IGNORE_OUTPUT primitive
#          # using plot_gallery=0 to avoid building examples
#          sphinx-build -M doctest docs/source/ docs/build/ -D plot_gallery=0 -v $_doctest_files
      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: docs/build
          preview-branch: main
          umbrella-dir: docs/pr-preview
          pages-base-path: docs

#jobs:
#  deploy-preview:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - run: npm i && npm run build
#        if: github.event.action != 'closed'
#      - uses: rossjrw/pr-preview-action@v1
#        with:
#          source-dir: build
#          preview-branch: main
#          umbrella-dir: docs/pr-preview
#          pages-base-path: docs
